[package]
name = "mmproxy"
description = "Rust implementation of mmproxy (TCP + UDP)"
repository = "https://github.com/saiko-tech/mmproxy-rs"
version = "0.2.2"
edition = "2024"
license = "MIT"

[dependencies]
log = "0.4"
env_logger = "0.11"
argwerk = "0.20"
cidr = "0.3"
proxy-protocol = "0.5"
libc = "0.2"
simple-eyre = "0.3"
socket2 = { version = "0.5", features = [ "all" ] }
tokio = { version = "1.48", features = [ "net", "rt-multi-thread", "macros", "io-util", "sync", "time" ] }
num_cpus = "1.17.0"
tokio-util = "0.7.17"
